version: '3.8'

x-omnistrate-service-plan:
  name: 'DataLab AI Data Processing Platform - Fully Managed - Free Tier'
  tenancyType: 'OMNISTRATE_MULTI_TENANCY'
  deployment:
    hostedDeployment:
      AwsAccountId: '541226919566'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::541226919566:role/omnistrate-bootstrap-role'
  pricing:
    - dimension: cpu
      unit: cores
      timeUnit: hour
      price: 0.0
    - dimension: memory
      unit: GiB
      timeUnit: hour
      price: 0.0
    - dimension: storage
      unit: GiB
      timeUnit: hour
      price: 0.0
  validPaymentMethodRequired: false
  maxNumberOfInstancesAllowed: 1

# Exports to cloud-provider specific monitoring and logging services aggregated and tagged across tenants and deployments
x-internal-integrations:
  metrics:
    provider: native
  logs:
    provider: native

services:
  datalab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    privileged: true
    x-omnistrate-capabilities:
      autoscaling:
        maxReplicas: 1
        minReplicas: 1
      serverlessConfiguration:
        enableAutoStop: true
        targetPort: 3000
      httpReverseProxy:
        targetPort: 3000
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=file:/app/data/prisma/dev.db
      - NEXTAUTH_URL={{ $sys.network.externalClusterEndpoint }}
      - NEXTAUTH_SECRET={{ $func.random(string, 32) }}
      - ANTHROPIC_API_KEY={{ $var.anthropicApiKey }}
    volumes:
      - datalab_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.datalab.description=DataLab AI Data Processing Platform"
      - "com.datalab.version=1.0"
    x-omnistrate-api-params:
      - key: anthropicApiKey
        description: Anthropic API key
        name: Anthropic API key
        type: Password
        export: true
        required: true
        modifiable: true

volumes:
  datalab_data:
    driver: local
x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: ${{ secrets.GitHubPAT }}
      username: aloknikhil
